#!/bin/sh

echo +++ custom_z7io_payload_acq424.init 01

mkdir -p /dev/gpio/LED
for site in 1 2
do
	mkdir -p /dev/sites/$site
	cp /usr/local/init/CUSTOM_PMOD_1_E42410999.fru /dev/sites/$site/eeprom
	echo 1 > /dev/gpio/pmod${site}_present
	echo 1 > /dev/gpio/LED/FMC${site}_G
done

mkdir -p /mnt/local/cal
mount /usr/local/init/acq424_cal*img /mnt/local/cal

echo "custom_z7io_payload=placeholder" > /tmp/u-boot_env

echo +++ custom_z7io_payload_acq424.init 99
